% CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

function createFigure(X1, Y1, xTicks, yTicks, xlab, ylab, lnWidth, fontSize)

%  Auto-generated by MATLAB on 23-Oct-2015 18:33:40

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',lnWidth,...
    'XTick',xTicks,'yTick', yTicks, 'xLim',[xTicks(1) xTicks(length(xTicks))],'yLim',[yTicks(1) yTicks(length(yTicks))],...
    'FontSize',fontSize);
box(axes1,'on');
hold(axes1,'on');
xlabel(xlab, 'Interpreter','LaTeX' ); ylabel(ylab,'Interpreter','LaTeX');
set(gca, 'Layer','top')

% Create plot
plot(X1,Y1,'LineWidth',2);

